export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/ui/native/qsc_releases/software/chip/component/camx.qclinux.0.0/"
export TAG="260529"
export DISTRO="prebuilt_resolute"
export PACKAGE_NAME="qcom-camera_1.0.0-1_arm64.tar.gz"
